development:
  adapter: mysql2
  database: gem_listing_dev
  username: root
  encoding: utf8

test:
  adapter: mysql2
  database: gem_listing_test
  username: root
  encoding: utf8

production:
  adapter: mysql2
  database: gem_listing_prod
  username: root
  encoding: utf8
